apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-vm-arm
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora-vm-arm
    spec:
      domain:
        cpu:
          cores: 2
        machine:
          type: virt
        devices:
          disks:
            - name: datavolumedisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2Gi
      architecture: arm64
      networks:
        - name: default
          pod: {}
      volumes:
        - name: datavolumedisk
          dataVolume:
            name: fedora-cloud-arm-dv
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              ssh_pwauth: True
